"""
F-19-A: Contextual chunk enrichment (Anthropic Contextual Retrieval).

Before embedding, each child chunk gets a short 50-100 token prefix situating
it within the document (book/chapter/topic), generated by an LLM that has the
whole document (or a truncated window of it) cached — so only the first call
pays full price; the rest read the cached prefix at a fraction of the cost.

embedding_text (prefix + original) is what gets embedded/BM25-indexed.
original_text (unprefixed) is what the LLM sees at generation time — the
prefix would otherwise pollute every answer with a repeated preamble.
"""
import logging
import os
from concurrent.futures import ThreadPoolExecutor, as_completed

import anthropic

logger = logging.getLogger(__name__)

CONTEXTUALISER_ENABLED = os.environ.get("CONTEXTUALISER_ENABLED", "true").lower() == "true"
CONTEXTUALISER_MODEL = os.environ.get("CONTEXTUALISER_MODEL", "claude-haiku-4-5-20251001")
CONTEXTUALISER_MAX_TOKENS = int(os.environ.get("CONTEXTUALISER_MAX_TOKENS", "150"))
CONTEXTUALISER_MAX_DOC_TOKENS = int(os.environ.get("CONTEXTUALISER_MAX_DOC_TOKENS", "100000"))
CONTEXTUALISER_BATCH_SIZE = int(os.environ.get("CONTEXTUALISER_BATCH_SIZE", "10"))
CONTEXTUALISER_VERSION = int(os.environ.get("CONTEXTUALISER_VERSION", "1"))

# USD / 1M tokens — see F-19 §12.1. Cache write/read priced separately from a
# fresh (uncached) input token; blended Haiku rates, matches the worked example
# in the retrieval architecture doc.
CACHE_WRITE_COST_PER_1M = 0.30
CACHE_READ_COST_PER_1M = 0.03
FRESH_INPUT_COST_PER_1M = 0.25
OUTPUT_COST_PER_1M = 1.25

_FILE_TYPE_LABELS = {
    "pdf": "textbook",
    "pptx": "lecture slide deck",
    "docx": "lecture notes document",
    "mp4": "lecture video transcript",
    "mkv": "lecture video transcript",
    "mp3": "lecture audio transcript",
    "m4a": "lecture audio transcript",
}

_CONTEXTUALISER_PROMPT_TEMPLATE = """Here is the chunk we want to situate within the whole document:
<chunk>
{chunk_content}
</chunk>

This document is a {doc_type} used in {dept_name} at an Indian {college_type} college.

Give a short, succinct context (50-100 tokens) to situate this chunk within the
overall document, for the purpose of improving search retrieval of the chunk.
Include: the book/document name, the chapter or section it belongs to, the page,
and the specific topic or entity being discussed (drug name, anatomical structure,
disease, algorithm, circuit type, etc.).

Answer only with the succinct context and nothing else."""

_client: anthropic.Anthropic | None = None


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    return _client


def doc_type_label(file_type: str) -> str:
    return _FILE_TYPE_LABELS.get(file_type, "academic document")


def select_context_window(whole_document_text: str) -> str:
    """
    Sending an entire 1000-page textbook as context for every chunk is wasteful
    even with caching. Caps to CONTEXTUALISER_MAX_DOC_TOKENS via a straight
    truncation — F-13-A chapter maps aren't available yet at this point in the
    pipeline (chapter extraction runs as a follow-on job after main ingestion
    completes), so a chapter-scoped window isn't an option here.
    """
    max_chars = CONTEXTUALISER_MAX_DOC_TOKENS * 4  # ~4 chars/token heuristic
    if len(whole_document_text) <= max_chars:
        return whole_document_text
    return whole_document_text[:max_chars]


def _contextualise_one(doc_context: str, child: dict, doc_type: str, dept_name: str, college_type: str) -> dict:
    client = _get_client()
    chunk_prompt = _CONTEXTUALISER_PROMPT_TEMPLATE.format(
        chunk_content=child["text"],
        doc_type=doc_type,
        dept_name=dept_name or "the department",
        college_type=college_type or "engineering",
    )

    try:
        response = client.messages.create(
            model=CONTEXTUALISER_MODEL,
            max_tokens=CONTEXTUALISER_MAX_TOKENS,
            messages=[{
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": f"<document>\n{doc_context}\n</document>",
                        # ── Cache breakpoint — first chunk writes, rest read ──
                        "cache_control": {"type": "ephemeral"},
                    },
                    {"type": "text", "text": chunk_prompt},
                ],
            }],
        )

        context_prefix = response.content[0].text.strip()
        cache_read = getattr(response.usage, "cache_read_input_tokens", 0) or 0
        cache_write = getattr(response.usage, "cache_creation_input_tokens", 0) or 0
        fresh_input = response.usage.input_tokens
        output_tokens = response.usage.output_tokens

        cost_usd = (
            cache_write * CACHE_WRITE_COST_PER_1M
            + cache_read * CACHE_READ_COST_PER_1M
            + fresh_input * FRESH_INPUT_COST_PER_1M
            + output_tokens * OUTPUT_COST_PER_1M
        ) / 1_000_000

    except Exception as exc:
        logger.warning("Contextualiser call failed, chunk will embed without a context prefix: %s", exc)
        context_prefix = ""
        cache_read = cache_write = 0
        cost_usd = 0.0

    return {
        **child,
        "metadata": {
            **child["metadata"],
            "context_prefix": context_prefix,
            "contextualised": bool(context_prefix),
            "contextualiser_version": CONTEXTUALISER_VERSION,
        },
        "original_text": child["text"],
        "context_prefix": context_prefix,
        "embedding_text": f"{context_prefix}\n\n{child['text']}" if context_prefix else child["text"],
        "contextualiser_cost_usd": cost_usd,
        "cache_read_tokens": cache_read,
        "cache_write_tokens": cache_write,
    }


def contextualise_children(
    children: list[dict],
    whole_document_text: str,
    file_type: str,
    dept_name: str,
    college_type: str,
) -> tuple[list[dict], float]:
    """
    Adds embedding_text/original_text/context_prefix/contextualiser_* fields to
    every child chunk. Returns (contextualised_children, total_cost_usd).

    If disabled (or given no chunks), children pass through with embedding_text
    falling back to the raw chunk text, at zero cost.
    """
    if not CONTEXTUALISER_ENABLED or not children:
        passthrough = [
            {
                **c,
                "metadata": {**c["metadata"], "context_prefix": "", "contextualised": False},
                "original_text": c["text"],
                "context_prefix": "",
                "embedding_text": c["text"],
            }
            for c in children
        ]
        return passthrough, 0.0

    doc_context = select_context_window(whole_document_text)
    doc_type = doc_type_label(file_type)

    results: list[dict | None] = [None] * len(children)
    total_cost = 0.0

    # Prime the cache with ONE synchronous call before fanning out. Anthropic's
    # prompt cache is only populated once a cache-writing response completes —
    # firing all N chunks concurrently from the start means the first wave (up
    # to CONTEXTUALISER_BATCH_SIZE of them) all race to write the same ~100k-
    # token document context instead of 1 write + (N-1) cheap reads. This is
    # what the "1 write, then reads" cost math in the module docstring assumes;
    # without priming, actual spend can run many times the ~$4/textbook estimate.
    first_result = _contextualise_one(doc_context, children[0], doc_type, dept_name, college_type)
    results[0] = first_result
    total_cost += first_result["contextualiser_cost_usd"]

    remaining = children[1:]
    if remaining:
        with ThreadPoolExecutor(max_workers=CONTEXTUALISER_BATCH_SIZE) as pool:
            future_to_idx = {
                pool.submit(_contextualise_one, doc_context, child, doc_type, dept_name, college_type): i + 1
                for i, child in enumerate(remaining)
            }
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                result = future.result()
                results[idx] = result
                total_cost += result["contextualiser_cost_usd"]

    return results, round(total_cost, 6)  # type: ignore[return-value]
